#line 2 "pylex.yy.c"

#line 4 "pylex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[431] =
    {   0,
       58,   56,   57,   55,   56,   57,   45,   57,   36,   56,
       57,   56,   57,   56,   57,   56,   57,    7,   56,   57,
       56,   57,   16,   56,   57,   19,   56,   57,    7,   56,
       57,   21,   56,   57,   21,   56,   57,    7,   56,   57,
       28,   29,   56,   57,   25,   28,   29,   56,   57,    7,
       56,   57,    7,   56,   57,   53,   56,   57,   53,   56,
       57,   53,   56,   57,   53,   56,   57,   53,   56,   57,
       17,   56,   57,   56,   57,   20,   56,   57,   53,   56,
       57,   53,   56,   57,   53,   56,   57,   53,   56,   57,
       53,   56,   57,   53,   56,   57,   53,   56,   57,   53,

       56,   57,   53,   56,   57,   53,   56,   57,   53,   56,
       57,   53,   56,   57,   53,   56,   57,   53,   56,   57,
       53,   56,   57,   53,   56,   57,   15,   56,   57,    7,
       21,   56,   57,   18,   56,   57,    8,   56,   57,   55,
       56,   57,   43,   45,   57,   36,   56,   57,   56,   57,
       53,   56,   57,   53,   56,   57,   53,   56,   57,   53,
       56,   57,   53,   56,   57,   53,   56,   57,   53,   56,
       57,   53,   56,   57,   53,   56,   57,   53,   56,   57,
       53,   56,   57,   53,   56,   57,   53,   56,   57,   53,
       56,   57,   53,   56,   57,   53,   56,   57,   53,   56,

       57,   53,   56,   57,   53,   56,   57,   46,    5,   10,
       39,    7,    9,    1,   27,    6,   26,   28,   29,   32,
       33,   25,   28,   29,   25,    3,    4,    2,   53,   53,
       53,   53,   41,   53,   53,16436,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,16436,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   13,   44,
       46,   42,   42,   34,   42,   37,   39,   53,   53,   53,
       53,   53,16436,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,16436,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   10,   40,    9,    1,   31,

        6,   26,   30,   24,   28,   23,   22,    3,    2,   53,
       53,   53,   54,   49,   48,   51,   54, 8244,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   14,   35,   38,
       53,   53,   53,   47,   48,   51,   54,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   27,   26,   32,   53,
       50,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   12,   11,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53
    } ;

static yyconst flex_int16_t yy_accept[323] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   16,
       18,   21,   23,   26,   29,   32,   35,   38,   41,   45,
       50,   53,   56,   59,   62,   65,   68,   71,   74,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  134,  137,
      140,  143,  146,  149,  151,  154,  157,  160,  163,  166,
      169,  172,  175,  178,  181,  184,  187,  190,  193,  196,
      199,  202,  205,  208,  209,  210,  210,  211,  211,  211,
      212,  213,  213,  214,  214,  215,  216,  217,  218,  220,
      220,  220,  222,  222,  222,  225,  226,  227,  228,  229,

      230,  231,  232,  232,  232,  232,  233,  234,  235,  237,
      238,  239,  240,  241,  242,  243,  244,  245,  246,  247,
      249,  250,  251,  252,  253,  254,  255,  256,  257,  258,
      259,  260,  262,  263,  264,  265,  265,  266,  266,  268,
      269,  270,  271,  272,  274,  275,  276,  277,  278,  279,
      280,  281,  282,  283,  284,  286,  287,  288,  289,  290,
      291,  292,  293,  294,  295,  296,  297,  297,  297,  297,
      298,  299,  299,  299,  299,  300,  300,  301,  302,  303,
      303,  304,  305,  305,  306,  307,  308,  309,  310,  311,
      312,  312,  313,  314,  315,  318,  319,  320,  321,  322,

      323,  324,  325,  326,  327,  328,  329,  330,  331,  332,
      333,  334,  335,  336,  337,  338,  339,  340,  340,  341,
      342,  343,  344,  348,  349,  350,  351,  352,  353,  354,
      355,  356,  357,  358,  359,  360,  361,  362,  363,  364,
      365,  366,  367,  367,  367,  367,  367,  367,  367,  367,
      368,  368,  369,  370,  371,  372,  373,  374,  375,  376,
      377,  378,  379,  380,  381,  382,  383,  384,  385,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  395,  396,
      397,  398,  399,  400,  401,  401,  401,  401,  401,  401,
      401,  402,  403,  404,  405,  406,  407,  408,  409,  410,

      411,  412,  413,  414,  415,  416,  417,  418,  419,  420,
      421,  422,  423,  424,  425,  426,  427,  428,  429,  430,
      431,  431
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,    9,   10,   11,
       12,   13,   14,   15,   14,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   15,   15,   22,
       23,   24,    1,   15,   25,   26,   25,   25,   27,   28,
       29,   29,   29,   30,   29,   31,   29,   32,   33,   29,
       29,   34,   29,   35,   34,   29,   29,   36,   29,   29,
       37,   38,   39,    9,   29,   40,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   30,   50,   51,   52,   53,
       54,   55,   29,   56,   57,   58,   59,   29,   60,   61,
       62,   29,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    5,    1,
        5,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    5,    5,    5,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    5,    1,    5,    1,
        6,    6,    6,    6,    6,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    5,    5,    5,    1
    } ;

static yyconst flex_int16_t yy_base[340] =
    {   0,
        0,   65,  636,  637,  637,    0,  637,  612,   64,   71,
      611,   66,  637,  637,   56,  637,   62,   55,  112,  158,
       62,   64,    0,  592,  578,   84,  575,  637,   86,  637,
       39,  574,   44,  584,   52,   80,  577,   94,  586,  572,
      569,  583,  142,  567,   95,  573,  637,  598,  637,  637,
        0,    0,  153,  156,  579,  565,  562,   48,  561,   99,
      571,  111,  114,  564,  129,  573,  559,  556,  570,  157,
      554,  142,  560,  637,  637,  158,  601,  189,  196,    0,
      637,  131,  597,  201,  583,  192,  582,  196,  209,  188,
      224,  637,  213,    0,    0,  637,  581,  637,  580,    0,

      551,  548,  211,  210,  231,  541,  214,  555,  253,  553,
      556,  543,  200,  204,  552,  541,  537,  538,  537,  533,
      534,  536,  220,  530,  537,  527,  522,  534,  524,  536,
      637,  637,  637,    0,    0,  277,  256,  268,    0,  529,
      526,  519,  533,  242,  531,  534,  521,  235,  234,  530,
      519,  515,  516,  515,  245,  513,  515,  231,  509,  516,
      506,  501,  513,  503,  515,  637,  250,  256,  267,  637,
      637,  277,  283,  285,  637,  293,  637,  637,  306,  320,
      637,  278,  310,  324,  328,    0,  637,  637,  502,  513,
      294,  512,  637,    0,  637,    0,  511,  514,  497,  495,

      506,  506,  505,  508,  496,  505,  492,  503,  493,  486,
      485,  482,  489,  491,  487,  637,  637,  305,  637,  480,
      491,  490,  637,  489,  492,  475,  473,  484,  484,  483,
      486,  474,  483,  470,  481,  471,  464,  463,  457,  464,
      466,  437,  299,  312,  349,  325,  339,  352,  339,  346,
      350,  354,  637,  442,  637,  430,  431,  423,  430,  419,
      422,  431,  403,  409,  398,  406,  390,  400,  400,  390,
      365,  366,  358,  365,  351,  354,  363,  347,  358,  347,
      355,  343,  353,  353,  354,  355,  371,  369,  370,  372,
      338,  342,  336,  340,  339,  331,  347,  344,  333,  327,

      269,  262,  252,  249,  240,  199,  165,  148,  374,  373,
      138,  132,  143,  112,   75,   94,   81,   73,   72,   64,
      637,  412,  419,  426,  433,  435,  442,  449,  456,  463,
      470,   93,  477,  484,  491,  498,  505,  512,   72
    } ;

static yyconst flex_int16_t yy_def[340] =
    {   0,
      321,    1,  321,  321,  321,  322,  321,  321,  323,  324,
      321,  325,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  326,  326,  326,  326,  326,  321,  321,  321,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  321,  321,  321,  321,
      327,  328,  329,  330,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  321,  321,  323,  321,  323,  324,  331,
      321,  325,  321,  325,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  332,   20,  321,  321,  321,  321,  326,

      326,  326,  323,  325,  321,  326,  321,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  109,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      321,  321,  321,  333,  334,  329,  335,  330,  331,  326,
      326,  326,  326,  109,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  109,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  321,  336,  323,  323,  321,
      321,  337,  325,  325,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  332,  321,  321,  326,  326,
      321,  326,  321,  338,  321,  339,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  321,  321,  335,  321,  326,
      326,  326,  321,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  336,  336,  336,  337,  337,  337,  321,  321,
      321,  321,  321,  326,  321,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  336,  336,  336,  337,  337,  337,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  336,  337,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
        0,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321
    } ;

static yyconst flex_int16_t yy_nxt[704] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   11,   16,   17,   18,   19,   20,   20,
       20,   21,   11,   22,   23,   23,   23,   24,   23,   23,
       23,   25,   23,   26,   27,   23,   28,   29,   30,   16,
       31,   32,   33,   34,   35,   36,   37,   23,   38,   23,
       39,   23,   40,   41,   42,   43,   23,   44,   26,   45,
       23,   46,   47,   48,   49,   50,   51,   52,   85,   53,
       77,   87,   54,   80,   80,   83,  196,   81,   81,   86,
       86,   86,   86,   97,   81,   98,   81,   99,  107,  107,
      103,  108,   55,  104,  111,  109,   56,  112,  186,   57,

      143,   78,  114,   84,  144,   58,   59,   60,   61,   62,
       63,   64,  115,   65,  155,   66,  155,   67,   68,   69,
       70,  105,   71,  120,   72,  120,   73,   88,  116,   89,
       89,   89,   89,  117,  320,  118,  155,   90,   91,  120,
      171,   92,  128,  129,   93,  121,  120,   94,  103,  146,
      120,  104,  147,   90,  134,  135,   91,  136,  139,  139,
      137,  149,  151,  103,  166,   93,  104,  152,   84,  153,
      319,  150,   94,   88,  155,   95,   95,   95,   95,  105,
      156,  155,  125,  318,   91,  155,  126,   92,   96,  163,
      164,  168,  169,  120,  105,   78,  317,  160,   80,   80,

      155,  161,   91,  173,  174,  182,  182,  316,   96,   86,
       86,   86,   86,  179,  179,  179,  179,   77,  176,   83,
      103,  177,  180,  104,   88,  181,   89,   89,   89,   89,
      185,  185,  185,  191,  191,   91,  176,  183,   92,  155,
      180,  184,  184,  184,  184,  120,  223,   84,   78,  223,
      120,  105,  201,   91,  193,  194,  244,  195,  219,  219,
      202,  196,  166,  196,  196,  196,  196,  196,  196,  196,
      139,  139,  209,  166,  196,  196,  196,  120,  134,  135,
      155,  136,  228,  236,  137,  155,  247,  245,  155,  196,
      229,  196,  171,   78,  171,  182,  182,  155,  224,  155,

      103,  100,  315,  104,   78,  244,  249,  219,  219,  197,
      250,  250,  250,  250,  248,  196,  196,  196,  285,  155,
       84,  314,   84,  179,  179,  179,  179,  184,  184,  184,
      184,  105,  180,  251,  247,  181,  245,  252,  252,  252,
      252,  184,  184,  184,  184,  185,  185,  185,  288,  245,
      180,  286,  287,  253,  289,  290,  250,  250,  250,  250,
      309,  244,  248,  250,  250,  250,  250,  252,  252,  252,
      252,  252,  252,  252,  252,  177,  248,  244,  310,  247,
      309,  247,  310,  181,  155,  120,  313,  120,  120,  120,
      312,  245,  245,  120,  311,  120,  155,  155,  308,  155,

      307,  306,  305,  304,  303,  302,  248,  248,  245,  248,
      248,  245,   74,  301,  155,  155,   74,   74,   74,   76,
      300,   76,   76,   76,   76,   76,   79,   79,   79,   79,
       79,   79,   79,   82,  155,   82,   82,   82,   82,   82,
      100,  100,  131,  120,  120,  299,  131,  131,  131,  132,
      120,  298,  297,  132,  132,  132,  133,  133,  296,  133,
      133,  133,  133,  138,  138,  138,  138,  138,  138,  138,
      170,  295,  294,  293,  170,  170,  170,  216,  292,  120,
      120,  216,  216,  216,  217,  291,  120,  284,  217,  217,
      217,  218,  218,  218,  218,  218,  218,  218,  243,  243,

      243,  243,  243,  243,  243,  246,  246,  246,  246,  246,
      246,  246,  255,  155,  283,  282,  255,  255,  255,  281,
      155,  280,  279,  278,  277,  155,  276,  275,  155,  155,
      274,  273,  272,  271,  155,  155,  270,  269,  120,  268,
      267,  266,  120,  265,  264,  263,  262,  120,  261,  260,
      120,  120,  259,  258,  257,  256,  120,  120,  254,  242,
      241,  240,  155,  239,  238,  237,  235,  234,  233,  232,
      155,  231,  230,  227,  226,  225,  155,  222,  221,  220,
      215,  214,  213,  120,  212,  211,  210,  208,  207,  100,
      206,  205,  120,  204,  203,  200,  199,  198,  120,  192,

      190,  189,  188,  187,  178,  175,  172,  167,  165,  162,
      159,  155,  158,  157,  154,  148,  145,  142,  141,  140,
       81,  130,  127,  124,  120,  123,  122,  119,  113,  110,
      106,  102,  101,   81,   75,  321,    3,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321
    } ;

static yyconst flex_int16_t yy_chk[704] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,   15,    2,
        9,   18,    2,   10,   10,   12,  339,   18,   15,   17,
       17,   17,   17,   21,   21,   21,   22,   22,   29,   29,
       26,   31,    2,   26,   33,   31,    2,   33,  332,    2,

       58,    9,   35,   12,   58,    2,    2,    2,    2,    2,
        2,    2,   35,    2,  320,    2,  319,    2,    2,    2,
        2,   26,    2,  318,    2,  317,    2,   19,   36,   19,
       19,   19,   19,   36,  316,   36,  315,   19,   19,   38,
       82,   19,   45,   45,   19,   38,   38,   19,   43,   60,
       38,   43,   60,   19,   53,   53,   19,   53,   54,   54,
       53,   62,   63,   70,   76,   19,   70,   63,   82,   63,
      314,   62,   19,   20,   65,   20,   20,   20,   20,   43,
       65,   65,   43,  313,   20,   65,   43,   20,   20,   72,
       72,   78,   78,  312,   70,   76,  311,   70,   79,   79,

      308,   70,   20,   84,   84,   90,   90,  307,   20,   86,
       86,   86,   86,   88,   88,   88,   88,  103,   86,  104,
      107,   86,   88,  107,   89,   88,   89,   89,   89,   89,
       93,   93,   93,  105,  105,   89,   86,   91,   89,  306,
       88,   91,   91,   91,   91,  113,  144,  104,  103,  155,
      113,  107,  114,   89,  109,  109,  167,  109,  137,  137,
      114,  109,  168,  109,  109,  109,  109,  109,  109,  109,
      138,  138,  123,  169,  109,  109,  109,  123,  136,  136,
      148,  136,  149,  158,  136,  148,  172,  167,  158,  109,
      149,  109,  173,  168,  174,  182,  182,  305,  144,  304,

      191,  155,  303,  191,  169,  243,  176,  218,  218,  109,
      176,  176,  176,  176,  172,  109,  109,  109,  244,  302,
      173,  301,  174,  179,  179,  179,  179,  183,  183,  183,
      183,  191,  179,  180,  246,  179,  243,  180,  180,  180,
      180,  184,  184,  184,  184,  185,  185,  185,  247,  244,
      179,  245,  245,  184,  248,  248,  249,  249,  249,  249,
      285,  286,  246,  250,  250,  250,  250,  251,  251,  251,
      251,  252,  252,  252,  252,  250,  247,  287,  288,  289,
      309,  290,  310,  252,  300,  299,  298,  297,  296,  295,
      294,  285,  286,  293,  292,  291,  284,  283,  282,  281,

      280,  279,  278,  277,  276,  275,  288,  289,  287,  290,
      310,  309,  322,  274,  273,  272,  322,  322,  322,  323,
      271,  323,  323,  323,  323,  323,  324,  324,  324,  324,
      324,  324,  324,  325,  270,  325,  325,  325,  325,  325,
      326,  326,  327,  269,  268,  267,  327,  327,  327,  328,
      266,  265,  264,  328,  328,  328,  329,  329,  263,  329,
      329,  329,  329,  330,  330,  330,  330,  330,  330,  330,
      331,  262,  261,  260,  331,  331,  331,  333,  259,  258,
      257,  333,  333,  333,  334,  256,  254,  242,  334,  334,
      334,  335,  335,  335,  335,  335,  335,  335,  336,  336,

      336,  336,  336,  336,  336,  337,  337,  337,  337,  337,
      337,  337,  338,  241,  240,  239,  338,  338,  338,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  222,  221,  220,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  192,  190,  189,  165,
      164,  163,  162,  161,  160,  159,  157,  156,  154,  153,
      152,  151,  150,  147,  146,  145,  143,  142,  141,  140,
      130,  129,  128,  127,  126,  125,  124,  122,  121,  120,
      119,  118,  117,  116,  115,  112,  111,  110,  108,  106,

      102,  101,   99,   97,   87,   85,   83,   77,   73,   71,
       69,   68,   67,   66,   64,   61,   59,   57,   56,   55,
       48,   46,   44,   42,   41,   40,   39,   37,   34,   32,
       27,   25,   24,   11,    8,    3,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pylex.l"
/*
Name: Arun Baskar
UID : u0811338
Project done with Arvind Haran
*/
#line 8 "pylex.l"
#include "string.h"
char* LStrip(char* str);
char* RStrip(char* str);
char* Strip(char* str);

int current = 0;
int continuation = 0;
struct list* create_list(int val);
struct list* addElementToList(int val);
void removeElement();
void empty_list();
void handle_indent();
int replaceChar(char *data, char search, char replace);
struct list
{
    int val;
    struct list *next;
};

struct list *head = NULL;
int curly=0, brac=0, squarebrac =0;
#line 816 "pylex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 78 "pylex.l"


#line 1009 "pylex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 322 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 637 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 80 "pylex.l"
{
                           printf("(PUNCT \"%s\")\n", yytext);
                         }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "pylex.l"
{
                                          printf("(PUNCT \"%s\")\n", yytext);
                                      }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "pylex.l"
{
                                          printf("(PUNCT \"%s\")\n", yytext);
                                      }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "pylex.l"
{
                             printf("(PUNCT \"%s\")\n", yytext);
                         }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "pylex.l"
{
                      printf("(PUNCT \"%s\")\n", yytext);
                  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "pylex.l"
{
                                  printf("(PUNCT \"%s\")\n", yytext);

                              }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "pylex.l"
{
                            printf("(PUNCT \"%s\")\n", yytext);
                          }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "pylex.l"
{
                           printf("(PUNCT \"%s\")\n", yytext);
                        }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 114 "pylex.l"
{
                   char *new_str = (char*)malloc(strlen(yytext) + 100);
                   char *new_str_ = (char*)malloc(strlen(yytext) + 100);
                   yytext[strlen(yytext) -1] = '\0';
                   yytext++;
                   ReplaceStr(yytext, "\\\n", new_str, "");
                   ReplaceStr(new_str, "\n", new_str_, "\\n");
                   ReplaceStr(new_str_, "'", new_str, "\'");
                   ReplaceStr(new_str, "\"", new_str_, "\"");
                   ReplaceStr(new_str_, "\a", new_str, "\\a");
                   ReplaceStr(new_str, "\b", new_str_, "\\b");
                   ReplaceStr(new_str_, "\f", new_str, "\\f");
                   ReplaceStr(new_str, "\r", new_str_, "\\r");
                   ReplaceStr(new_str_, "\t", new_str, "\\t");
                   ReplaceStr(new_str, "\v", new_str_, "\\v");
                   printf("(LIT \"%s\")\n", new_str_);
                   free(new_str);
                   free(new_str_);
               }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 134 "pylex.l"
{
                       char *new_str = (char*)malloc(strlen(yytext) + 100);
                       char *new_str_ = (char*)malloc(strlen(yytext) + 100);
                       yytext[strlen(yytext) -1] = '\0';
                       yytext++;
                       ReplaceStr(yytext, "\\\n", new_str, "");
                       ReplaceStr(new_str, "\n", new_str_, "\\n");
                       ReplaceStr(new_str_, "'", new_str, "\'");
                       ReplaceStr(new_str, "\\\"", new_str_, "\\\"");
                       ReplaceStr(new_str, "\"", new_str_, "\"");
                       ReplaceStr(new_str_, "\a", new_str, "\\a");
                       ReplaceStr(new_str, "\b", new_str_, "\\b");
                       ReplaceStr(new_str_, "\f", new_str, "\\f");
                       ReplaceStr(new_str, "\r", new_str_, "\\r");
                       ReplaceStr(new_str_, "\t", new_str, "\\t");
                       ReplaceStr(new_str, "\v", new_str_, "\\v");
                       printf("(LIT \"%s\")\n", new_str_);
                       free(new_str);
                       free(new_str_);
                   }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 155 "pylex.l"
{
           char *new_str = (char*)malloc(strlen(yytext) + 100);
           char *new_str_ = (char*)malloc(strlen(yytext) + 100);
           ReplaceStr(yytext, "'''", new_str_, "");
           ReplaceStr(new_str_, "\\\n", new_str, "");
           ReplaceStr(new_str, "\n", new_str_, "\\n");
           ReplaceStr(new_str_, "\'", new_str, "\\\'");
           ReplaceStr(new_str, "\\\"", new_str_, "\\\\\""); 
           ReplaceStr(new_str, "\"", new_str_, "\\\"");
           ReplaceStr(new_str_, "\a", new_str, "\\a");
           ReplaceStr(new_str, "\b", new_str_, "\\b");
           ReplaceStr(new_str_, "\f", new_str, "\\f");
           ReplaceStr(new_str, "\r", new_str_, "\\r");
           ReplaceStr(new_str_, "\t", new_str, "\\t");
           ReplaceStr(new_str, "\v", new_str_, "\\v");
           printf("(LIT \"%s\")\n", new_str_);
           free(new_str);
           free(new_str_);
       }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 175 "pylex.l"
{
                 char *new_str = (char*)malloc(strlen(yytext) + 100);
                 char *new_str_ = (char*)malloc(strlen(yytext) + 100);
                 ReplaceStr(yytext, "\"\"\"", new_str_, "");
                 ReplaceStr(new_str_, "\\\n", new_str, "");
                 ReplaceStr(new_str, "\n", new_str_, "\\n"); 
                 ReplaceStr(new_str_, "\'", new_str, "\\\'");
                 ReplaceStr(new_str, "\"", new_str_, "\\\"");
                 ReplaceStr(new_str_, "\a", new_str, "\\a");
                 ReplaceStr(new_str, "\b", new_str_, "\\b");
                 ReplaceStr(new_str_, "\f", new_str, "\\f");
                 ReplaceStr(new_str, "\r", new_str_, "\\r");
                 ReplaceStr(new_str_, "\t", new_str, "\\t");
                 ReplaceStr(new_str, "\v", new_str_, "\\v");
                 printf("(LIT \"%s\")\n", new_str_);
                 free(new_str);
                 free(new_str_);
             }
	YY_BREAK
case 13:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 194 "pylex.l"
{
                         printf("ERROR: Incorrect Indentation1\n");
                     }
	YY_BREAK
case 14:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 198 "pylex.l"
{
                                printf("ERROR: Incorrect Indentation2\n");
                            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 202 "pylex.l"
{
                      curly++; 
                      printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 207 "pylex.l"
{
                      brac++;
                      printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 212 "pylex.l"
{
                      squarebrac++;
                      printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 217 "pylex.l"
{
                      curly--;
                      printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 222 "pylex.l"
{
                      brac--;
                      printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 227 "pylex.l"
{
                      squarebrac--;
                      printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 232 "pylex.l"
{
                   printf("(PUNCT \"%s\")\n", yytext);
                 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 236 "pylex.l"
{
                                           /*HEX*/
                                           yytext[0] = 35;
                                           printf("(LIT %s)\n", yytext);
                                      }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 242 "pylex.l"
{
                                           /*OCT*/
                                           yytext[0] = 35;
                                           printf("(LIT %s)\n", yytext);
                                      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 248 "pylex.l"
{
                                          /*BINARY*/
                                          yytext[0] = 35;
                                          printf("(LIT %s)\n", yytext);
                                      }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 254 "pylex.l"
{
                                           /*DECIMAL*/
                                           printf("(LIT %s)\n", yytext);
                                       }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 259 "pylex.l"
{
                                                       printf("(LIT %s)\n", yytext);
                                                  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 263 "pylex.l"
{
                                                       printf("(LIT %s)\n", yytext);
                                                }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 267 "pylex.l"
{
                                                     printf("(LIT %s)\n", yytext);
                                                }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 271 "pylex.l"
{
                                    printf("(LIT %s)\n", yytext);
                               }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 275 "pylex.l"
{
                                                       yytext[strlen(yytext)-1] = 105;
                                                       printf("(LIT +%s)\n", yytext);
                                                  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 280 "pylex.l"
{
                                                       yytext[strlen(yytext)-1] = 105;
                                                       printf("(LIT +%s)\n", yytext);
                                                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 285 "pylex.l"
{
                                                     yytext[strlen(yytext)-1] = 105;
                                                     printf("(LIT +%s)\n", yytext);
                                                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 290 "pylex.l"
{
                                    yytext[strlen(yytext)-1] = 105;
                                    printf("(LIT +%s)\n", yytext);
                               }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 295 "pylex.l"
{
                                  continuation = 0;
                                 /*if(!(brac|squarebrac|curly))
                                     printf("(NEWLINE)\n");*/
                             }
	YY_BREAK
case 35:
/* rule 35 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 301 "pylex.l"
{
                                               continuation = 0;
                                               empty_list();
                                               /*if(!(brac|squarebrac|curly))
                                                     printf("(NEWLINE)\n");*/
                                          }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 309 "pylex.l"
{
            }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 312 "pylex.l"
{
                                   continuation = 0;
                               }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 316 "pylex.l"
{
                                          continuation = 0;
                                      }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 320 "pylex.l"
{
                               continuation = 0;
                               if(!(brac|squarebrac|curly))
                                   printf("(NEWLINE)\n");
                            }
	YY_BREAK
case 40:
/* rule 40 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 326 "pylex.l"
{
                               continuation = 0;
                               if(!(brac|squarebrac|curly))
                                   printf("(NEWLINE)\n");
                               empty_list();
                            }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 333 "pylex.l"
{
                          continuation = 1;
                        }
	YY_BREAK
case 42:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 337 "pylex.l"
{
                            if(!continuation)
                            {
                            handle_indent(); 
                            }
                          }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 344 "pylex.l"
{
                 /*if(!(brac|squarebrac|curly))
                     printf("(NEWLINE)\n");*/
                 continuation = 0;
            }
	YY_BREAK
case 44:
/* rule 44 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 350 "pylex.l"
{
                            continuation = 0;
                            if(!(brac|squarebrac|curly))
                            {
                            /*printf("(NEWLINE)\n");*/
                            empty_list();
                            }
                         }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 360 "pylex.l"
{
                   continuation = 0;
                   if(!(brac|squarebrac|curly))
                       printf("(NEWLINE)\n");
             }
	YY_BREAK
case 46:
/* rule 46 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 367 "pylex.l"
{
                         continuation = 0;
                         if(!(brac|squarebrac|curly))
                         { 
                          printf("(NEWLINE)\n");
                          empty_list();
                         }
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 376 "pylex.l"
{
                       Strip(yytext);
                       printf("(KEYWORD %s)\n", yytext);
                   }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 381 "pylex.l"
{
                       Strip(yytext);
                       printf("(KEYWORD %s)\n", yytext);
                  }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 386 "pylex.l"
{
                        continuation = 0;
                        Strip(yytext);
                        printf("(KEYWORD %s)\n", yytext);
                        if(!(brac|squarebrac|curly))
                            printf("(NEWLINE)\n");
                    }
	YY_BREAK
case 50:
/* rule 50 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 394 "pylex.l"
{
                                   continuation = 0;
                                   Strip(yytext);
                                   printf("(KEYWORD %s)\n", yytext);
                                   if(!(brac|squarebrac|curly))
                                       printf("(NEWLINE)\n");
                                   empty_list();
                                 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 403 "pylex.l"
{
                            Strip(yytext);
                            printf("(KEYWORD %s)\n", yytext);
                         }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 408 "pylex.l"
{
                            Strip(yytext);
                            printf("(KEYWORD %s)\n", yytext);
                         }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 413 "pylex.l"
{
                 printf("(ID \"%s\")\n", yytext);
            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 417 "pylex.l"
{
                            Strip(yytext);
                            printf("(KEYWORD %s)\n", yytext);
                          }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 422 "pylex.l"
{
               empty_list();
               printf("(ENDMARKER)\n");
               yyterminate(); 
           }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 428 "pylex.l"
{}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 431 "pylex.l"
{
              printf("(ERROR)\n");
          }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 434 "pylex.l"
ECHO;
	YY_BREAK
#line 1688 "pylex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 322 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 322 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 321);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 434 "pylex.l"



int main( int argc, char **argv )
{
     ++argv, --argc;  /* skip over program name */
     if ( argc > 0 )
             yyin = fopen( argv[0], "r" );
     else
             yyin = stdin;
     create_list(0);
     yylex();
}

char* LStrip(char* str)
{
    int i = 0, j = 0, size;

    if(NULL == str)
        return str;

    size = strlen((char *)str);
    if(size == 0)
        return str;

    while(str[i] == ' ' || str[i] == '\t' || str[i] == '\r' || str[i] == '\n')
        i++;

    if(i == 0)
        return str;

    for(j = 0; i < size; j++, i++)
        str[j] = str[i];
    str[j] = 0;

    return str;
}

char* RStrip(char* str)
{
    int i = 0, size;

    if(NULL == str)
        return str;

    size = strlen((char *)str);
    if(size == 0)
        return str;

    i = size - 1;

    while(str[i] == ' ' || str[i] == '\n' || str[i] == '\r' || str[i] == '\t')
        str[i--] = 0;

    return str;
}

char* Strip(char* str)
{
    LStrip(str);
    RStrip(str);
    return str;
}

struct list* create_list(int val)
{
    struct list* temp = (struct list*)malloc(sizeof(struct list));
    if(NULL == temp)
    {
        return NULL;
    }
    temp->val = val;
    temp->next = NULL;

    head = temp;
    return temp;
}

struct list* addElementToList(int val)
{
    struct list *ptr = (struct list*)malloc(sizeof(struct list));
    if(NULL == ptr)
    {
        return NULL;
    }
    ptr->val = val;
    ptr->next = head;

    head = ptr;
    return ptr;
}

void removeElement()
{
    struct list *temp;
    temp = head;
    head = head->next;
    temp->next = NULL;
    free(temp);
}

void empty_list()
{
    while(head->val != 0)
    {
            printf("(DEDENT)\n");
            removeElement();
    }
}

void handle_indent()
{
    if(brac|squarebrac|curly)
    {
        return;
    }

    if(head->val == 0)
	{
	addElementToList(strlen(yytext));
	printf("(INDENT)\n", head->val);
	}
    else
    {
	if(strlen(yytext) > head->val)
	{
	    addElementToList(strlen(yytext));
	    printf("(INDENT)\n", head->val);
	}
        else if(strlen(yytext) == head->val)
        {
            return;
        }
	else
	{
	    while(head->val !=0)
	    {
		removeElement();
		if(strlen(yytext) > head->val)
		{
		    printf("(DEDENT)\n");
		    printf("(ERROR \"mis-indented program\")\n");
		    break;
		}
		else if(strlen(yytext) == head->val)
		{
		    printf("(DEDENT)\n");
		    break;
		}
                else if(strlen(yytext) < head->val)
                {
                    printf("(DEDENT)\n");
                }
	    }
	}
    }
}

void print_ele()
{
    struct list *temp;
    temp = head;
    while(temp != NULL)
    {
        printf("%d-", temp->val);
        temp = temp->next;
    }
}

int replaceChar(char *data, char search, char replace)
{
    while(*data != '\0')
    {
        if (*data == search)
        {
            *data = replace;
        }
        data ++;
    }
    return 0;
}

void ReplaceStr(char * old_data, char * old_str, char * new_data, char * new_str){
    char * pre = old_data;
    char * next= old_data;
    int old_str_len = strlen(old_str);
    int new_str_len = strlen(new_str);
    int new_pos = 0;
    int size = 0;
    do{
        next = strstr(next, old_str);
        if (NULL != next)
            size = strlen(pre)-strlen(next);
        else
            size = strlen(pre);
        memcpy(new_data + new_pos, pre, size);
        new_pos += size;
        if (NULL != next){
            memcpy(new_data + new_pos, new_str, new_str_len);
            new_pos += new_str_len;
            next     = next + old_str_len;
            pre      = next;
        }
   }while(NULL != next);
    memcpy(new_data + new_pos, "\0", 1);
}

/*
Name: Arun Baskar
UID : u0811338
Project done with Arvind Haran
*/

